import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import LayoutWithNavbar from "../components/LayoutWithNavbar";
import { AuthProvider } from "../context/AuthContext";

export const metadata: Metadata = {
  title: "CourseSite",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={
          inter.className + " flex flex-col min-h-screen bg-black text-gray-100"
        }
      >
        <AuthProvider>
          <LayoutWithNavbar />
          <main className="flex-grow pt-20">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
