import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import LayoutWithNavbar from "../components/LayoutWithNavbar";
import { AuthProvider } from "../context/AuthContext";
import { FloatingGuidancePayment } from "../components/PaymentDialog";
import { ModalProvider } from "../context/ModalContext";

export const metadata: Metadata = {
  title: "Bold Voice Systems",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={
          inter.className +
          " flex flex-col min-h-screen bg-black text-gray-100"
        }
      >
        <AuthProvider>
          <ModalProvider>
            <LayoutWithNavbar />
            {/* Added pb-24 only for small screens to avoid overlap with floating button */}
            <main className="flex-grow pt-20 pb-24 sm:pb-0">{children}</main>
            <FloatingGuidancePayment />
            <Footer />
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
